## Read data using pandas

In [1]:
import pandas as pd
import tensorflow as tf

In [2]:
csv_file = tf.keras.utils.get_file('heart.csv', 
                                   'https://storage.googleapis.com/applied-dl/heart.csv')

16384/13273 [=====================================] - 0s 0us/step


In [33]:
df = pd.read_csv(csv_file)

In [34]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca        thal  target  
0   0       fixed       0  
1   3      normal       1  
2   2  reversible       0  
3   0      normal       0  
4   0      normal       0

In [35]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal         object
target        int64
dtype: object

`thal` is `object`, now we'll convert it to discrete numerical value.

In [36]:
df['thal'] = pd.Categorical(df['thal'])
print(df['thal'])
print(df.thal.cat.codes)
df['thal'] = df.thal.cat.codes

0           fixed
1          normal
2      reversible
3          normal
4          normal
          ...    
298         fixed
299    reversible
300    reversible
301    reversible
302    reversible
Name: thal, Length: 303, dtype: category
Categories (5, object): [1, 2, fixed, normal, reversible]
0      2
1      3
2      4
3      3
4      3
      ..
298    2
299    4
300    4
301    4
302    4
Length: 303, dtype: int8


In [37]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca  thal  target  
0   0     2       0  
1   3     3       1  
2   2     4       0  
3   0     3       0  
4   0     3       0

## Load data using `tf.data.Dataset`

In [38]:
target = df.pop('target')
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca  thal  
0   0     2  
1   3     3  
2   2     4  
3   0     3  
4   0     3

In [47]:
df.values

array([[63.,  1.,  1., ...,  3.,  0.,  2.],
       [67.,  1.,  4., ...,  2.,  3.,  3.],
       [67.,  1.,  4., ...,  2.,  2.,  4.],
       ...,
       [65.,  1.,  4., ...,  2.,  1.,  4.],
       [48.,  1.,  4., ...,  1.,  2.,  4.],
       [63.,  0.,  4., ...,  2.,  3.,  4.]])

In [39]:
target.values

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,

In [40]:
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))

In [41]:
for features, label in dataset.take(1):
    print('Features: ',features.numpy())
    print('Target: ', label.numpy())

Features:  [ 63.    1.    1.  145.  233.    1.    2.  150.    0.    2.3   3.    0.
   2. ]
Target:  0


In [17]:
train_dataset = dataset.shuffle(len(df)).batch(1)

## Create and train a model

In [18]:
def get_compiled_model():
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(10, activation='relu'),
        tf.keras.layers.Dense(10, activation='relu'),
        tf.keras.layers.Dense(1)
    ])
    
    model.compile(
        optimizer=tf.optimizers.Adam(),
        loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
        metrics=['accuracy']
    )
    
    return model

In [19]:
model = get_compiled_model()
model.fit(train_dataset, epochs=15)

Epoch 1/15

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

303/303 [==============================] - 1s 2ms/step - loss: 1.5464 - accuracy: 0.6865
Epoch 2/15
303/303 [==============================] - 1s 2ms/step - loss: 0.6924 - accuracy: 0.7360
Epoch 3/15
303/303 [==============================] - 1s 2ms/step - loss: 0.6360 - accuracy: 0.7360
Epoch 4/15
303/303 [==============================] - 1s 2ms/step - loss: 0.7113 - accuracy: 0.7195
Epoch 5/15
303/303 [==============================] - 1s 2ms/step - loss: 0.6739 - accuracy: 0.7162
Epoch 6/

## Alternative to feature columns

In [20]:
inputs = {
    key: tf.keras.layers.Input(shape=(), name=key) for key in df.keys()
}

inputs

{'age': <tf.Tensor 'age:0' shape=(None,) dtype=float32>,
 'sex': <tf.Tensor 'sex:0' shape=(None,) dtype=float32>,
 'cp': <tf.Tensor 'cp:0' shape=(None,) dtype=float32>,
 'trestbps': <tf.Tensor 'trestbps:0' shape=(None,) dtype=float32>,
 'chol': <tf.Tensor 'chol:0' shape=(None,) dtype=float32>,
 'fbs': <tf.Tensor 'fbs:0' shape=(None,) dtype=float32>,
 'restecg': <tf.Tensor 'restecg:0' shape=(None,) dtype=float32>,
 'thalach': <tf.Tensor 'thalach:0' shape=(None,) dtype=float32>,
 'exang': <tf.Tensor 'exang:0' shape=(None,) dtype=float32>,
 'oldpeak': <tf.Tensor 'oldpeak:0' shape=(None,) dtype=float32>,
 'slope': <tf.Tensor 'slope:0' shape=(None,) dtype=float32>,
 'ca': <tf.Tensor 'ca:0' shape=(None,) dtype=float32>,
 'thal': <tf.Tensor 'thal:0' shape=(None,) dtype=float32>}

In [22]:
inputs.values(), list(inputs.values())

(dict_values([<tf.Tensor 'age:0' shape=(None,) dtype=float32>, <tf.Tensor 'sex:0' shape=(None,) dtype=float32>, <tf.Tensor 'cp:0' shape=(None,) dtype=float32>, <tf.Tensor 'trestbps:0' shape=(None,) dtype=float32>, <tf.Tensor 'chol:0' shape=(None,) dtype=float32>, <tf.Tensor 'fbs:0' shape=(None,) dtype=float32>, <tf.Tensor 'restecg:0' shape=(None,) dtype=float32>, <tf.Tensor 'thalach:0' shape=(None,) dtype=float32>, <tf.Tensor 'exang:0' shape=(None,) dtype=float32>, <tf.Tensor 'oldpeak:0' shape=(None,) dtype=float32>, <tf.Tensor 'slope:0' shape=(None,) dtype=float32>, <tf.Tensor 'ca:0' shape=(None,) dtype=float32>, <tf.Tensor 'thal:0' shape=(None,) dtype=float32>]),
 [<tf.Tensor 'age:0' shape=(None,) dtype=float32>,
  <tf.Tensor 'sex:0' shape=(None,) dtype=float32>,
  <tf.Tensor 'cp:0' shape=(None,) dtype=float32>,
  <tf.Tensor 'trestbps:0' shape=(None,) dtype=float32>,
  <tf.Tensor 'chol:0' shape=(None,) dtype=float32>,
  <tf.Tensor 'fbs:0' shape=(None,) dtype=float32>,
  <tf.Tensor 'r

In [25]:
x = tf.stack(list(inputs.values()), axis=-1)
x

<tf.Tensor 'stack_2:0' shape=(None, 13) dtype=float32>

In [26]:
x = tf.keras.layers.Dense(10, activation='relu')(x)
output = tf.keras.layers.Dense(1)(x)

In [27]:
model_func = tf.keras.Model(inputs=inputs, outputs=output)
model_func.compile(
    optimizer='adam',
    loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
    metrics=['accuracy']
)

In [28]:
df.to_dict('list')

{'age': [63,
  67,
  67,
  37,
  41,
  56,
  62,
  57,
  63,
  53,
  57,
  56,
  56,
  44,
  52,
  57,
  48,
  54,
  48,
  49,
  64,
  58,
  58,
  58,
  60,
  50,
  58,
  66,
  43,
  40,
  69,
  60,
  64,
  59,
  44,
  42,
  43,
  57,
  55,
  61,
  65,
  65,
  67,
  62,
  65,
  44,
  65,
  60,
  51,
  48,
  58,
  45,
  53,
  39,
  68,
  52,
  44,
  47,
  53,
  51,
  66,
  62,
  62,
  44,
  63,
  52,
  62,
  41,
  58,
  35,
  63,
  51,
  55,
  65,
  45,
  56,
  54,
  44,
  62,
  54,
  51,
  29,
  51,
  43,
  55,
  70,
  62,
  35,
  51,
  59,
  59,
  52,
  64,
  58,
  47,
  57,
  41,
  45,
  60,
  52,
  42,
  67,
  55,
  64,
  70,
  51,
  58,
  60,
  68,
  46,
  77,
  54,
  58,
  48,
  57,
  54,
  35,
  45,
  70,
  53,
  59,
  62,
  64,
  57,
  52,
  56,
  43,
  53,
  48,
  56,
  42,
  59,
  60,
  63,
  42,
  66,
  54,
  69,
  50,
  51,
  62,
  68,
  67,
  69,
  45,
  50,
  59,
  50,
  64,
  57,
  64,
  43,
  45,
  58,
  50,
  55,
  62,
  37,
  38,
  41,
  66,
  52,
  56,
  46,
  46,
  6

In [44]:
target.values[:10]

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 0])

In [49]:
dict_slices = tf.data.Dataset.from_tensor_slices((df.to_dict('list'), target.values)).batch(16)

In [46]:
for dict_slice in dict_slices.take(1):
    print(dict_slice)

({'age': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([63], dtype=int32)>, 'sex': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>, 'cp': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>, 'trestbps': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([145], dtype=int32)>, 'chol': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([233], dtype=int32)>, 'fbs': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>, 'restecg': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([2], dtype=int32)>, 'thalach': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([150], dtype=int32)>, 'exang': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([0], dtype=int32)>, 'oldpeak': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.3], dtype=float32)>, 'slope': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>, 'ca': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([0], dtype=int32)>, 'thal': <tf.Tensor: shape=(1,), dtype=int32, numpy=ar

In [50]:
model_func.fit(dict_slices, epochs=15)

Epoch 1/15
19/19 [==============================] - 0s 4ms/step - loss: 0.3642 - accuracy: 0.8251
Epoch 2/15
19/19 [==============================] - 0s 3ms/step - loss: 0.3522 - accuracy: 0.8152
Epoch 3/15
19/19 [==============================] - 0s 3ms/step - loss: 0.3517 - accuracy: 0.8152
Epoch 4/15
19/19 [==============================] - 0s 3ms/step - loss: 0.3517 - accuracy: 0.8119
Epoch 5/15
19/19 [==============================] - 0s 3ms/step - loss: 0.3508 - accuracy: 0.8185
Epoch 6/15
19/19 [==============================] - 0s 3ms/step - loss: 0.3508 - accuracy: 0.8251
Epoch 7/15
19/19 [==============================] - 0s 3ms/step - loss: 0.3504 - accuracy: 0.8251
Epoch 8/15
19/19 [==============================] - 0s 3ms/step - loss: 0.3501 - accuracy: 0.8251
Epoch 9/15
19/19 [==============================] - 0s 3ms/step - loss: 0.3499 - accuracy: 0.8251
Epoch 10/15
19/19 [==============================] - 0s 3ms/step - loss: 0.3497 - accuracy: 0.8251
Epoch 11/15
19/19 [

## References
- https://www.tensorflow.org/tutorials/load_data/pandas_dataframe